name: Upload component

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  upload_components:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Upload to ESP Component Registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: "u8g2: ."
          namespace: "nixy4"

          # Fallback to API token from repository secrets when OIDC cannot be used.
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
